### ISSUE TITLE
Feedback after coding day 1

### ISSUE THREAD

**Issue by LeBoucEtMistere** [skyzh/mini-lsm#11]
Hey,
Discovered this project recently and I find it super interesting, I had a very superficial understanding of LSM engines having worked a little with Cassandra, but I never had the time and need to dig in and understand how it works in details. This tutorial sparked the motivation to do so and so far I find it really interesting! Thanks for taking your time to build such interesting learning resources.

I just finished the day 1 part for now but I feel that I have a bit of feedback to give:
- I took me some time to understand that it's normal and expected that the `BlockBuilder::add` method is not responsible for sorting the entries of the block, but that instead the caller is responsible to insert entries in sorted order. After thinking quite a bit about it it finally made sense because blocks (and SSTables) are crafted from the in-memory tables and we therefore have all the data available when building a block, but it was not clear in the text and I spent some time wondering why we were implementing a bisect search in the block iterator while we didn't enforce any sorting in the block building.
- Some things doesn't feel really "rusty". I'm thinking about the iterator interface you designed for BlockIterator, which looks really different from iterators we are used to have in rust. In particular, the idea of "invalidating" the iterator by using empty vecs as key and value when we consume all the iterator, looks really different from the pattern of the `next` method returning an `Option<T>`, with `None` marking end of iteration. This is not bad per se, this custom iterator having different requirements, but it's a bit surprising. 
- I think your unit tests could have more coverage, and also be split into smaller tests that do test a single property. For instance, when in the tutorial you specify a property like "Key length and value length are 2B, which means their maximum length is 65536.", I'm expecting to see a unit test that will cover this property and make sure it is enforced. I did some of this in my day 1 work in my fork if you wanna check it out (https://github.com/LeBoucEtMistere/mini-lsm/pull/1)
- I think the tutorial steps could provide clearer entry points in code, i.e. "to solve this task, you will need to implement function in XXX".
- I noticed you liberally use `as` conversions in your solution, they tend to be risky especially when you convert to a more restrictive type, e.g. `usize` to `u16`. In that case it's best to use `try_into` to handle the case in which the conversion fails. That's not a big deal but since that's a tutorial it's always nice to leave a note about this to teach people about the risks of `as` conversions :)
- I never used the `bytes` crate before so I had to spend some time reading the doc and understanding how it works by looking at the solution code. I would have loved it if there was a note in the tutorial that mentioned it would be wise to leverage this crate to build the solution (because it is not mentioned anywhere except in the solution so I suspect many people might not know it's available to help), and maybe also giving a very quick example in the tutorial of how it can help playing with bytes.
- In the part about the encoding of blocks, you give great schemas of the format, but I would also have loved seeing a concrete example to make it clearer, with actual example data.
- I would have loved seeing some pointers to crates/algorithms in the extra tasks. I'm not very familiar with algos for compression/checksums, especially in the context of LSM engines, and it felt quite hard to explore this topic without a few pointers.

These are just a bunch of suggestions from my personal experience but I hope it helps you make your tutorial even better. Thanks for the great work, looking forward to working on day 2 tasks :D 🚀 !

**Comment by skyzh** [comment]
Thanks a lot!

**Comment by qgaye** [comment]
> * I took me some time to understand that it's normal and expected that the `BlockBuilder::add` method is not responsible for sorting the entries of the block, but that instead the caller is responsible to insert entries in sorted order. After thinking quite a bit about it it finally made sense because blocks (and SSTables) are crafted from the in-memory tables and we therefore have all the data available when building a block, but it was not clear in the text and I spent some time wondering why we were implementing a bisect search in the block iterator while we didn't enforce any sorting in the block building.

Strongly Agree

**Comment by gj-zhang** [comment]
@LeBoucEtMistere 

> I took me some time to understand that it's normal and expected that the BlockBuilder::add method is not responsible for sorting the entries of the block, but that instead the caller is responsible to insert entries in sorted order. After thinking quite a bit about it it finally made sense because blocks (and SSTables) are crafted from the in-memory tables and we therefore have all the data available when building a block, but it was not clear in the text and I spent some time wondering why we were implementing a bisect search in the block iterator while we didn't enforce any sorting in the block building.

Can you explain it further? I still don't understand.. Thank you.

**Comment by LeBoucEtMistere** [comment]
The SSTable is a durable storage primitive that is created by the DB once it needs to flush some in-memory data to disk. Therefore, the DB has total control on what data it puts in the SSTable and when it decides to create one. It does so when it has at least enough in memory-data to fully populate a single block (although this is just a required condition, I imagine it makes more sense to have more than one block before flushing). Since the DB is the one responsible to insert the records in the block and it knows them all before doing so, it can sort this data and insert it in the block while protecting this invariant that all the records in a block must be sorted.

**Comment by skyzh** [comment]
Thanks for the feedbacks! I have rewritten everything up to what we had in 2023 and week/part 2 of this tutorial will be available soon! https://skyzh.github.io/mini-lsm/
