### ISSUE TITLE
chore: no compaction of L0 and L1 is triggered when L0'size reaches `level0_file_num_compaction_trigger`  in simple leveled

### ISSUE THREAD

**Issue by zztaki** [skyzh/mini-lsm#111]
Hello, I found a bug in `simple_leveled.rs`.

When the number of SSTs in L0 is larger than or equal to `level0_file_num_compaction_trigger`, we still recheck `size_ratio_percent`. This causes our L0 size to potentially exceed it.

https://github.com/skyzh/mini-lsm/blob/23802b23dda7664079b97170a00641be7b68a22b/mini-lsm/src/compact/simple_leveled.rs#L46-L72

![image](https://github.com/user-attachments/assets/a125f851-dbbc-4cfc-81ef-56f0f86cb696)

I'm not sure if I misunderstood the tutorial. :)

**Comment by skyzh** [comment]
Ahh, I missed it. Do you want to submit patches to fix it? Or I can fix it.

**Comment by zztaki** [comment]
Thank you for your reply. I would like to submit patches. :)
