### ISSUE TITLE
Why remove the `memtable` from `imm_memtables` in `LsmStorgae.sync()`?

### ISSUE THREAD

**Issue by qgaye** [skyzh/mini-lsm#12]
https://github.com/skyzh/mini-lsm/blob/130b47ba54929e4eb1f83f1dfef7d79a9cfbd6ca/mini-lsm/src/lsm_storage.rs#L165-L177

In `sync()` we push the `memtable` to `imm_memtables` first, but remove it during flush to ssTable. What's the reason for removing `memtable` from `imm_memtables`? If we do not remove it, we can get key-value in `imm_memtables` which is located in memory.

And what is the role of `imm_memtables` in LsmStorage? It's unclear to me.

**Comment by skyzh** [comment]
imm_memtables are immutable memtables. Memory is not unlimited, and it will eventually become full. We will need to flush those memtables to disk as SST files. After flushing to disk, you can read them from block cache, and we can also run background compaction so consolidate SSTs.

**Comment by qgaye** [comment]
Soga. I found that I overlooked block cache in SsTable.
There is another point I don't really understand. The variable `imm_memtable` seems to be only used for temporarily store `memtable`. Is this all its functions? or are other aspects ignored by me?

**Comment by skyzh** [comment]
In the future, we will have `flush` thread in the background, which flushes imm_memtable to disk. `sync` will be very light-weight. It will only do a `fsync` on WAL file.

**Comment by qgaye** [comment]
very much looking forward to the future chapter
