### ISSUE TITLE
documentation error in day1 task2

### ISSUE THREAD

**Issue by xiaguan** [skyzh/mini-lsm#37]
https://github.com/skyzh/mini-lsm/blob/210a1c66c17423654ec82046dbdf794dc4f05bfe/mini-lsm-book/src/week1-01-memtable.md?plain=1#L42C1-L42C17

 It seems that task2 does not require changing the `mem_table.rs`

**Comment by skyzh** [comment]
Yep, could you please submit a pull request to remove it?
