### ISSUE TITLE
simple_leveled compaction apply 

### ISSUE THREAD

**Issue by TheLudlows** [skyzh/mini-lsm#47]
in this fille [https://github.com/skyzh/mini-lsm/blob/main/mini-lsm/src/compact/simple_leveled.rs](https://github.com/skyzh/mini-lsm/blob/main/mini-lsm/src/compact/simple_leveled.rs)
```rust
let new_l0_sstables = snapshot
    .l0_sstables
    .iter()
    .copied()
    .filter(|x| !l0_ssts_compacted.remove(x))
    .collect::<Vec<_>>();
assert!(l0_ssts_compacted.is_empty());
snapshot.l0_sstables = new_l0_sstables;
```
snapshot.l0_sstables is lastest，l0_tables may be compacted by full compaction task,  l0_sstables may be empty, so i'm not sure this assert is right?

**Comment by skyzh** [comment]
Full compaction will only be triggered when compaction strategy is disabled. This is something we might redesign in the future.

**Comment by TheLudlows** [comment]
> Full compaction will only be triggered when compaction strategy is disabled. This is something we might redesign in the future.

ok，if there are multi compaction threads, do you plan to do that?

**Comment by skyzh** [comment]
that's part of the bonus task so I won't put it in the current solution
