### ISSUE TITLE
[Doc] Any plans to support chinese version tutorial

### ISSUE THREAD

**Issue by Gleiphir2769** [skyzh/mini-lsm#59]
Hi, I think this is a very good repository for understanding LSM and Rust. But I found that the tutorial does not seem to have a Chinese version, which seems to be difficult for non-English native developers to understand.

Do we have any plans to support chinese version tutorial? If not, I think I can help to support it.

**Comment by skyzh** [comment]
i don't think it's worth the effort to maintain two copies of this tutorial by myself. feel free to fork and translate :)
