### ISSUE TITLE
LsmStorage::scan does not include level 1-6 iterators

### ISSUE THREAD

**Issue by YangchenYe323** [skyzh/mini-lsm#6]
I noticed that the reference `scan` function in https://github.com/skyzh/mini-lsm/blob/main/mini-lsm/src/lsm_storage.rs doesn't include l1-l6 iterators. It stops at merging the `memtables` and the `l0_sstables`. Wondering if this is a mistake or there's a reason behind doing so. I would suppose `scan` would return an iterator over all the data in the storage?

**Comment by skyzh** [comment]
Up to part 4 we only have l0 SSTs. Other levels will be supported in the compaction chapter. Thanks for reporting!
