### ISSUE TITLE
Nextest required but not included

### ISSUE THREAD

**Issue by criccomini** [skyzh/mini-lsm#70]
Just a heads up: I followed the environment setup steps and was getting:

```
cargo nextest run
error: no such command: `nextest`

	Did you mean `test`?

	View all installed commands with `cargo --list`
	Find a package to install `nextest` with `cargo search cargo-nextest`
Error: command ["cargo", "nextest", "run"] exited with code 101
```

It looks like I had to `cargo install cargo-nextest` to get things working. Seems like this should be included in the environment setup docs.

**Comment by skyzh** [comment]
yep, i should have added it to the set up guide

**Comment by skyzh** [comment]
Just realized it is part of the `cargo x install-tools` command. Closing it for now.
