### ISSUE TITLE
question about `MergeIterator.next()`

### ISSUE THREAD

**Issue by qgaye** [skyzh/mini-lsm#8]
https://github.com/skyzh/mini-lsm/blob/9e1c0ca3229a28c19c36d0a597b619494652e3f4/mini-lsm/src/iterators/merge_iterator.rs#L129-L134

I'm not familiar with rust, so I do not clearly understand the meaning of `std::mem::swap(&mut *inner_iter, current)` here in `MergeIterator.next` impl.

I guess it maybe means that `heap.pop()` first, and then `heap.push(current)`? And why we have to use `swap` function here?

**Comment by skyzh** [comment]
Good question, and you are correct! Because we are using `peek_mut` here, swap is much more efficient.

**Comment by qgaye** [comment]
Got it. But there is still one thing I can't understand. `swap` here swap the `vec[0]` in `heap` to a new value, but how BinaryHeap automatically `sfit_down` the new value to correct position in `vec`? I tried to get answer from the Internet but had no luck. Hope can get your explanation.

```rust
let mut heap: BinaryHeap<i32> = BinaryHeap::new();
heap.push(1);
heap.push(2);
heap.push(3);
if let Some(a) = heap.peek_mut() {
   // found vec in heap is [3, 1, 2]
   std::mem::swap(&mut *a, &mut 0);
   // after swap, vec in heap is [2, 1, 0], why 0 can sfit_down to bottom
}
```

**Comment by skyzh** [comment]
When you drop the object acquired by `PeekMut`, it will automatically sift down.

https://doc.rust-lang.org/stable/src/alloc/collections/binary_heap.rs.html#293

**Comment by qgaye** [comment]
Amazing! thx.
