### ISSUE TITLE
Why does HeapWrapper use Box

### ISSUE THREAD

**Issue by Tianion** [skyzh/mini-lsm#9]
https://github.com/skyzh/mini-lsm/blob/130b47ba54929e4eb1f83f1dfef7d79a9cfbd6ca/mini-lsm/src/iterators/merge_iterator.rs#L9
I noticed that the 'Box' here seems to be unnecessary.
`struct HeapWrapper<I: StorageIterator>(pub usize, pub I)`  passes all tests. (I just delete all `Box::new()`)

**Comment by skyzh** [comment]
Good question! This would reduce the cost of moving things in the heap. The size of iterator might be very big if it is a two-merge iterator. If we are using box, swapping things in heap is just copying two usize.

**Comment by Tianion** [comment]
> The size of iterator might be very big if it is a two-merge iterator. 

You are right! I have considered this situation, but I didn't notice two-merge iterator. 
Box is more efficient than 'not Box', and the gap is obvious.
```
create not box          time:   [556.57 ns 561.23 ns 565.13 ns]
                        change: [-8.6674% -5.0631% -1.2081%] (p = 0.01 < 0.05)
                        Performance has improved.

create with box         time:   [308.17 ns 320.86 ns 337.43 ns]
                        change: [-22.489% -12.735% -1.8383%] (p = 0.04 < 0.05)
```
