### ISSUE TITLE
[Bug] compaction-simulator-ref leveled display bug

### ISSUE THREAD

**Issue by jiangwel** [skyzh/mini-lsm#90]
![image](https://github.com/user-attachments/assets/c27f1ae4-d56d-41b2-b85c-37238172d82a)
The SST IDs inserted in the compression plan for L4 should be the cumulative result of 1 and 2, which are 3 and 4.
However, after compression, the displayed SST IDs remain as the original 1 and 2.

**Comment by skyzh** [comment]
yes, but there are two modes for the compaction simulator, the show original ID mode, and the show new ID mode? you may tweak the cli parameters to get your desired result :)
