### ISSUE TITLE
document error in week2 day3

### ISSUE THREAD

**Issue by silver-ymz** [skyzh/mini-lsm#96]
About [`Triggered by Size Ratio`](https://skyzh.github.io/mini-lsm/week2-03-tiered.html#task-12-triggered-by-size-ratio) in [`Universal Compaction`](https://skyzh.github.io/mini-lsm/week2-03-tiered.html#task-1-universal-compaction), it says `For all tiers, if there is a tier n that size of all previous tiers / this tier >= (100 + size_ratio) * 100%, we will compact all n tiers.`

But according to the [docs](https://github.com/facebook/rocksdb/wiki/Universal-Compaction#:~:text=We%20start%20from,hold%20any%20more.) and [example](https://github.com/facebook/rocksdb/wiki/Universal-Compaction#:~:text=1%201%201%201%201%20%20%3D%3E%20%205%0A1%205%20%20(no%20compaction%20triggered)%0A1%201%205%20%20(no%20compaction%20triggered)%0A1%201%201%205%20%20(no%20compaction%20triggered)%0A1%201%201%201%205%20%20%3D%3E%204%205%0A1%204%205%20%20(no%20compaction%20triggered)%0A1%201%204%205%20%20(no%20compaction%20triggered)%0A1%201%201%204%205%20%3D%3E%203%204%205%0A1%203%204%205%20%20(no%20compaction%20triggered)%0A1%201%203%204%205%20%3D%3E%202%203%204%205) from `rocksdb`, it seems to compact previous `n - 1` tiers when `this tier / all previous tiers >= (100 + size_ratio) * 100%`

Is this a mistake?

**Comment by skyzh** [comment]
I think the RocksDB example is describing exactly what the tutorial is saying?

> We start from R1, if size(R2) / size(R1) <= size ratio trigger, then (R1, R2) are qualified to be compacted together. 

Consider R1 = 200MB, R2 = 100MB, size ratio trigger is 100, then we will trigger the compaction of R1+R2 to produce a new tier of 300MB.

**Comment by skyzh** [comment]
okay, now I understand your concern, we probably need to fix it :)

**Comment by skyzh** [comment]
you may help review https://github.com/skyzh/mini-lsm/pull/97, thanks :)
